Declare fprintf and fscanf wrappers in right order
UNIFYCR_WRAP(fscanf) calls UNIFYCR_WRAP(vfscanf) so declare
them in the proper order to avoid an implicit declaration
compiler warning. Likewise for fprintf and vfprintf.

Allowing checkpatch failure because of checkpatch.pl false
positive:

 ERROR: need consistent spacing around '*' (ctx:WxV)
 #2367: FILE: client/src/unifycr-stdio.c:1390:
 +int UNIFYCR_WRAP(fprintf)(FILE *stream, const char *format, ...)
                                ^
 ERROR: need consistent spacing around '*' (ctx:WxV)
 #2393: FILE: client/src/unifycr-stdio.c:1432:
 +int UNIFYCR_WRAP(fscanf)(FILE *stream, const char *format, ...)

TEST_CHECKPATCH_ALLOW_FAILURE=yes