Fix unused variables in meta/src/partitioner.c
This fixes the following compiler warnings:

../../../meta/src/partitioner.c: In function get_byte_num
../../../meta/src/partitioner.c:99:16: error: unused variable val
[-Werror=unused-variable]
  unsigned char val;
                ^
../../../meta/src/partitioner.c:98:6: error: unused variable i
[-Werror=unused-variable]
  int i;
      ^

../../../meta/src/partitioner.c: In function get_range_servers_from_range
../../../meta/src/partitioner.c:1009:33: error: unused variable new_stat
[-Werror=unused-variable]
   struct mdhim_stat *cur_stat, *new_stat;
                                 ^

../../../meta/src/partitioner.c:1031:33: error: unused variable new_stat
[-Werror=unused-variable]
   struct mdhim_stat *cur_stat, *new_stat;
                                 ^
../../../meta/src/partitioner.c:978:11: error: unused variable istat
[-Werror=unused-variable]
  uint64_t istat = 0;
           ^
../../../meta/src/partitioner.c:977:14: error: unused variable fstat
[-Werror=unused-variable]
  long double fstat = 0;
              ^
../../../meta/src/partitioner.c:976:6: error: unused variable float_type
[-Werror=unused-variable]
  int float_type = 0;
      ^
../../../meta/src/partitioner.c:972:17: error: unused variable cur_slice
[-Werror=unused-variable]
  int slice_num, cur_slice, start_slice, end_slice;
                 ^
../../../meta/src/partitioner.c:972:6: error: unused variable slice_num
[-Werror=unused-variable]
  int slice_num, cur_slice, start_slice, end_slice;
      ^