Fix bad typecasts in unifycr_init_pointers
- Fix the following compiler warnings:

unifycr.c(1319): error #2602: a value of type "unsigned long *" cannot
be assigned to an entity of type "off_t={__off_t={long}} *" due to
signedness
          unifycr_indices.ptr_num_entries = (unsigned long *)ptr;
                                          ^

unifycr.c(1327): error #2602: a value of type "unsigned long *" cannot
be assigned to an entity of type "off_t={__off_t={long}} *" due to
signedness
          unifycr_fattrs.ptr_num_entries = (unsigned long *)ptr;

- Clean up some style issues in the same function.